sudo: false

language: node_js

node_js:
  - "7"

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm test
  - npm run build

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
